### ISSUE TITLE
HOTLの今回の手法名を決める

### ISSUE THREAD

**Issue by fuyu-quant** [auto-res/researchgraph#21]
- HOTLはあくまでもAutoRes内のチーム名なのでSakanaAIの"AI scientist"のような名称を決めたいです．
- アイデアがあればこのissuesに返信する形でコメントをお願いします．

**Comment by wkumagai** [comment]
ChatGPTに生成させた候補

ResearchMind
理由: 研究を自動で進めるシステムであり、「Mind（知性・思考）」という言葉を用いることで、知的な研究サポートを行うイメージを強調。

AutoScholar
理由: 学者 (Scholar) の知識を自動化するイメージで、研究プロセス全体をカバーするシステムであることを強調。

InnoLab
理由: 「Innovation」と「Laboratory」を組み合わせた名前で、革新的なアイデアを生み出す自動研究システムとしての役割を強調。

DeepThinker
理由: ディープラーニングやAIを駆使した高度な思考を模倣するシステムであり、深い知識や洞察を提供する意味を込めている。

SynthesysAI
理由: 研究や情報の「統合 (Synthesis)」を自動的に行い、新しい知識を生み出すことを意図した名前。AIによる複雑な統合プロセスを強調。

AIgenius
理由: 研究者としての「天才的な」能力を模倣し、革新的な解決策を提案するシステムというイメージを持たせている。

EurekaLab
理由: 「Eureka（発見・閃き）」と「Lab（研究室）」を組み合わせた名前で、研究プロセスにおける新しい発見や画期的な結果を自動で生み出すことを表現。

NeuroSolver
理由: ニューラルネットワークと問題解決能力を組み合わせたシステムとして、複雑な課題に取り組み、解決策を見つける能力を強調。

AutoPioneer
理由: 研究分野における「パイオニア（開拓者）」として、未踏の領域を自動で探求・開発するシステムであることを表現。

LogicaAI
理由: 「論理（Logic）」と「AI」を組み合わせ、特に論理的思考や問題解決に優れた研究支援システムとしてのイメージを強調。

QuantumLab
理由: 「量子（Quantum）」という言葉は、最先端の科学技術を連想させ、非常に高度で精密な自動研究システムを示唆。研究の最前線に立つイメージを強調。

MetaResearcher
理由: メタ認知やメタデータの「メタ」と「研究者」を組み合わせ、システムが単なる研究だけでなく、その過程を深く分析し、新しい視点を提供することを強調。

CogniLab
理由: 「Cognition（認知）」と「Lab」を組み合わせた名前で、システムが高度な認知能力を持ち、複雑な問題を解決するという印象を与える。

AIcurius
理由: 「AI」と「Curious（好奇心）」を組み合わせた名前で、システムが常に新しい知識を追求し、革新的なアイデアを探索する姿勢を強調。

InnovAItion
理由: 「Innovation（革新）」と「AI」を組み合わせ、AIを通じて革新的な研究を推進するシステムとしての役割を強調。

SynthAI
理由: 「Synthesis（統合）」と「AI」を組み合わせ、システムが様々なデータや知識を統合して新しいアイデアや理論を生み出す機能を表現。

PrismAI
理由: プリズムのように複数の視点や情報を整理して、一つの光（解決策）として導き出すシステムをイメージ。複雑な研究課題の多面的なアプローチを強調。

IntelliForge
理由: 「Intelligence（知能）」と「Forge（鍛造）」を組み合わせ、知的な研究プロセスを自動的に形作り、強固な成果を生み出すイメージを強調。

AIxplore
理由: 「AI」と「Explore（探求）」を組み合わせ、システムが未知の領域やアイデアを積極的に探求し、革新をもたらす研究ツールであることを強調。

InsightMachine
理由: 洞察を自動的に生成するシステムとして、データや仮説から有益な結論を導き出す能力を強調。

**Comment by fuyu-quant** [comment]
LangGraphをベースに作成しているのでResearchGraphでもいいかと思いました．(そもそもこのOSS自体をResearchGraphにしてもいいかもしれませんが，，，)
LangGraphでは構成要素を繋げたものをGraphと表現しているので，AI scientisのResearchGraphや今回の手法のResearchGraphなどと一般名詞のように使ってもいいかと思いました．その場合今回の手法はResearchGraph-1(RG-1)とかになるのかもしれません．(新しい名称を作りすぎるのも良くないと思うので)

ただResearchGraphという言葉はすでに使われていました...
https://researchgraph.org/
上記はソフトウェアではなく組織を表しているみたいです．

**Comment by ryamauchi** [comment]
直球で AI-researcher はどうかと思いましたが、一般的すぎますかね。

一般に任意の処理の流れはグラフとして表現できるわけなので、ここでGraphという語を主題化するのは少し違うような気はしています。研究というプロセスをLLMを用いたループ処理で表現する、というのがHOTLでやっていることで、それを実装しようとしたらLangGraphを使うことになった、という流れなので。

本手法の重要なポイントは既存研究を自動で改善するところなので、AI research improver とかが実情に即しているかもしれません。これだと（ちょっとした改良ではなく）あくまで新規手法を提案しているという点が伝わりづらいかもですが。
